name: homarr-secured
services:
  app:
    image: ghcr.io/ajnart/homarr:dev
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
    ports:
      - target: 7575
        published: 7575
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/Homarr/configs
        target: /app/data/configs
      - type: bind
        source: /DATA/AppData/Config/Homarr/icons
        target: /app/public/icons
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Homarr is a simple and lightweight homepage for your server, that helps you easily access all of your services in one place.
  tagline:
    en_us: Homarr Is A Simple And Lightweight Homepage For Your Server, That Helps You Easily Access All Of Your Services In One Place.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/homarr.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/homarr.png
  title:
    en_us: Homarr Secured
  category: Tools
