name: davinci-postgres-server
services:
  app:
    image: postgres:13
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      POSTGRES_DB: ''
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
        - container: POSTGRES_DB
          description:
            en_us: ''
        - container: POSTGRES_USER
          description:
            en_us: ''
        - container: POSTGRES_PASSWORD
          description:
            en_us: ''
        - container: TZ
          description:
            en_us: ''
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/DavinciServer/
        target: /var/lib/postgresql/data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: DaVinci Resolve Postgresql Server, Davinci requires a specific version of postgres db, this container will install the version needed
  tagline:
    en_us: Davinci Resolve Postgresql Server, Davinci Requires A Specific Version Of Postgres Db, This Container Will Install The Version Needed
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/resolve.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/resolve.png
  title:
    en_us: Davinci Postgres Server
  category: Tool
