name: guacamole
services:
  app:
    image: oznu/guacamole:0.9.14
    restart: unless-stopped
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/Guacamole
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: A clientless remote desktop gateway.
  tagline:
    en_us: A Clientless Remote Desktop Gateway.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/guacamole.png
  thumbnail: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/guacamole.png
  title:
    en_us: Guacamole
  category: Other
  port_map: '8080'
