name: nginx-proxy-manager
services:
  app:
    image: jlesage/nginx-proxy-manager:v23.04.1
    restart: unless-stopped
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 80
        published: 8080
        protocol: tcp
      - target: 81
        published: 8181
        protocol: tcp
      - target: 443
        published: 4443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/Nginx-Proxy
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Nginx Proxy Manager enables you to easily forward to your websites running at home or otherwise, including free SSL, without having to know too much about Nginx or Letsencrypt.
  tagline:
    en_us: Nginx Proxy Manager Enables You To Easily Forward To Your Websites Running At Home Or Otherwise, Including Free Ssl, Without Having To Know Too Much About Nginx Or Letsencrypt.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/proxy_mgr.png
  thumbnail: https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/master/Images/proxy_mgr.png
  title:
    en_us: Nginx Proxy Manager
  category: Proxy
  port_map: '80'
