name: jenkins
services:
  app:
    image: jenkins/jenkins:2.411
    environment:
      JENKINS_OPTS: ''
    x-casaos:
      envs:
        - container: JENKINS_OPTS
          description:
            en_us: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 50000
        published: 50000
        protocol: tcp
    volumes: []
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Open-source continuous integration tool
  tagline:
    en_us: Open-source Continuous Integration Tool
  developer: ''
  author: WisdomSky
  icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/jenkins.png
  thumbnail: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/jenkins.png
  title:
    en_us: Jenkins
  category: continuous-integration
  port_map: '8080'
