name: pihole-doh/dot
services:
  app:
    image: oijkn/pihole-doh-dot:v1.4
    restart: unless-stopped
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp
      - target: 67
        published: 67
        protocol: udp
      - target: 1010
        published: 80
        protocol: tcp
      - target: 4443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/PiHole_DoH-DoT
        target: /etc/pihole
      - type: bind
        source: /DATA/AppData/Config/PiHole_DoH-DoT/DNS
        target: /etc/dnsmasq.d
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: A Linux network-level advertisement and Internet tracker blocking application which acts as a DNS sinkhole with both DoH (DNS over HTTPS) and DoT (DNS over TLS) clients.
  tagline:
    en_us: A Linux Network-level Advertisement And Internet Tracker Blocking Application Which Acts As A Dns Sinkhole With Both Doh (dns Over Https) And Dot (dns Over Tls) Clients.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/pihole_doh-dot.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/pihole_doh-dot.png
  title:
    en_us: Pi Hole Doh/dot
  category: Other
  port_map: '1010'
