name: urlwatch
services:
  app:
    image: mediadepot/urlwatch:master
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /opt/mediadepot/apps/urlwatch
        target: /srv/urlwatch/config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: A tool for monitoring webpages for updates
  tagline:
    en_us: A Tool For Monitoring Webpages For Updates
  developer: ''
  author: WisdomSky
  icon: https://mediadepot.github.io/templates/img/urlwatch.png
  thumbnail: https://mediadepot.github.io/templates/img/urlwatch.png
  title:
    en_us: Urlwatch
  category: 'Tools:'
