name: pgadmin
services:
  app:
    image: dpage/pgadmin4:7.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      PGADMIN_DEFAULT_EMAIL: ''
      PGADMIN_DEFAULT_PASSWORD: ''
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
        - container: PGADMIN_DEFAULT_EMAIL
          description:
            en_us: ''
        - container: PGADMIN_DEFAULT_PASSWORD
          description:
            en_us: ''
        - container: TZ
          description:
            en_us: ''
    ports:
      - target: 5050
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/pgadmin
        target: /var/lib/pgadmin
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: PGAdmin is a web-based GUI tool used to interact with the Postgres database sessions, both locally and remote servers as well. You can use PGAdmin to perform any sort of database administration required for a Postgres database.
  tagline:
    en_us: Pgadmin Is A Web-based Gui Tool Used To Interact With The Postgres Database Sessions, Both Locally And Remote Servers As Well. You Can Use Pgadmin To Perform Any Sort Of Database Administration Required For A Postgres Database.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/pgadmin.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/pgadmin.png
  title:
    en_us: Pgadmin
  category: Other
  port_map: '5050'
