name: filebrowser
services:
  app:
    image: filebrowser/filebrowser:v2-s6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
    ports:
      - target: 8082
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /portainer/Downloads
        target: /srv
      - type: bind
        source: /DATA/AppData/Config/filebrowser/filebrowser.db
        target: /database/filebrowser.db
      - type: bind
        source: /DATA/AppData/Config/filebrowser/settings.json
        target: /config/settings.json
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: arm Web File Browser which can be used as a middleware or standalone app.
  tagline:
    en_us: arm Web File Browser Which Can Be Used As A Middleware Or Standalone App.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/filebrowser.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/filebrowser.png
  title:
    en_us: Filebrowser S6
  category: Other
  port_map: '8082'
