name: apache-httpd
services:
  app:
    image: httpd:latest
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
    ports:
      - target: 8080
        published: 80
        protocol: tcp
      - target: 8443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/apache-httpd
        target: /usr/local/apache2/htdocs/
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: The Apache HTTP Server is a free and open-source cross-platform web server software, released under the terms of Apache License 2.0. Apache is developed and maintained by an open community of developers under the auspices of the Apache Software Foundation.
  tagline:
    en_us: The Apache Http Server Is A Free And Open-source Cross-platform Web Server Software, Released Under The Terms Of Apache License 2.0. Apache Is Developed And Maintained By An Open Community Of Developers Under The Auspices Of The Apache Software Foundation.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/apache-httpd.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/apache-httpd.png
  title:
    en_us: Apache Httpd
  category: Web
  port_map: '8080'
