name: httpd
services:
  app:
    image: httpd:latest
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes: []
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Open-source HTTP server
  tagline:
    en_us: Open-source Http Server
  developer: ''
  author: WisdomSky
  icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/httpd.png
  thumbnail: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/httpd.png
  title:
    en_us: Httpd
  category: webserver
  port_map: '80'
