name: libreddit
services:
  app:
    image: libreddit/libreddit:latest-arm
    restart: unless-stopped
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 8088
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/libreddit
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: An alternative private front-end to Reddit
  tagline:
    en_us: An Alternative Private Front-end To Reddit
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/libreddit.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/libreddit.png
  title:
    en_us: Libreddit
  category: Other
  port_map: '8088'
