name: minio
services:
  app:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z.hotfix.c5e012acf
    environment:
      MINIO_ACCESS_KEY: ''
      MINIO_SECRET_KEY: ''
    x-casaos:
      envs:
        - container: MINIO_ACCESS_KEY
          description:
            en_us: ''
        - container: MINIO_SECRET_KEY
          description:
            en_us: ''
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    volumes: []
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: A distributed object storage server built for cloud applications and devops
  tagline:
    en_us: A Distributed Object Storage Server Built For Cloud Applications And Devops
  developer: ''
  author: WisdomSky
  icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/minio.png
  thumbnail: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/minio.png
  title:
    en_us: Minio
  category: storage
