name: socks5-proxy
services:
  app:
    image: serjs/go-socks5-proxy:master
    restart: unless-stopped
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Simple socks5 server using go-socks5 with authentication options
  tagline:
    en_us: Simple Socks5 Server Using Go-socks5 With Authentication Options
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/socks5.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/socks5.png
  title:
    en_us: Go Socks5-proxy
  category: Proxy
  port_map: '8080'
